apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-no-privilege-escalation
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-no-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Containers must set allowPrivilegeEscalation to false."
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
